
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/DreamCloud
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      - db

  # MySQL-databasen
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: DreamCloud
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
